<?php

namespace AppBundle\Repository;

/**
 * SuperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuperRepository extends \Doctrine\ORM\EntityRepository
{
}
